//MATCH THRESHOLD VALUES 
export const FOCUS = 0.7;
export const INDEPENDENCE = 0.8;
export const CONFIDENCE = 0.8;


//CONSTANTS

export const NUMBER_OF_FOCUS_QUESTION = 7;
export const NUMBER_OF_ENERGY_QUESTION = 10;
export const NUMBER_OF_INDEPENDENCE_QUESTION = 5;
export const NUMBER_OF_CONFIDENCE_QUESTION = 6;

export const STEP_PERCENT = 100 / (NUMBER_OF_CONFIDENCE_QUESTION + NUMBER_OF_ENERGY_QUESTION + NUMBER_OF_INDEPENDENCE_QUESTION + NUMBER_OF_FOCUS_QUESTION)